/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-primary": "#ffffff",
          "tertiary-fixed": "#ffddb8",
          "on-primary-fixed": "#001f29",
          "surface-container-high": "#e2e7ff",
          "surface": "#faf8ff",
          "tertiary-fixed-dim": "#ffb95f",
          "on-surface": "#131b2e",
          "on-primary-fixed-variant": "#004d62",
          "on-error-container": "#93000a",
          "surface-container": "#eaedff",
          "on-tertiary-fixed": "#2a1700",
          "on-secondary": "#ffffff",
          "inverse-on-surface": "#eef0ff",
          "surface-tint": "#006781",
          "on-primary-container": "#d3f1ff",
          "on-background": "#131b2e",
          "on-secondary-fixed-variant": "#920028",
          "on-tertiary-container": "#ffe9d4",
          "tertiary": "#764900",
          "surface-container-low": "#f2f3ff",
          "tertiary-container": "#965f00",
          "secondary-fixed": "#ffdada",
          "secondary": "#ba0035",
          "inverse-primary": "#81d1f0",
          "on-secondary-container": "#fffbff",
          "on-tertiary-fixed-variant": "#653e00",
          "on-secondary-fixed": "#40000c",
          "secondary-container": "#e21e49",
          "on-surface-variant": "#3f484c",
          "outline-variant": "#bec8cd",
          "primary-container": "#0e7490",
          "surface-container-highest": "#dae2fd",
          "surface-container-lowest": "#ffffff",
          "surface-bright": "#faf8ff",
          "surface-variant": "#dae2fd",
          "secondary-fixed-dim": "#ffb3b6",
          "primary-fixed": "#b9eaff",
          "outline": "#6f787d",
          "error": "#ba1a1a",
          "background": "#faf8ff",
          "primary-fixed-dim": "#81d1f0",
          "surface-dim": "#d2d9f4",
          "inverse-surface": "#283044",
          "error-container": "#ffdad6",
          "on-error": "#ffffff",
          "primary": "#005a71",
          "on-tertiary": "#ffffff"
      },
      "spacing": {
          "stack-lg": "32px",
          "stack-sm": "8px",
          "stack-md": "16px",
          "container-padding": "24px",
          "unit": "4px",
          "gutter": "16px"
      },
      "fontFamily": {
          "label-caps": ["Inter", "sans-serif"],
          "button": ["Inter", "sans-serif"],
          "h1": ["Manrope", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "h2": ["Manrope", "sans-serif"],
          "body-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "button": ["16px", { "lineHeight": "1.0", "fontWeight": "600" }],
          "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
